repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: requirements-txt-fixer
  - repo: https://github.com/prettier/pre-commit
    rev: 413fd9da8e03249b74acf8543567e5debbad8bfa
    hooks:
      - id: prettier
        args: [--prose-wrap=always, --print-width=88]
  #- repo: https://github.com/mgedmin/check-manifest
  #  rev: "0.45"
  #  hooks:
  #    - id: check-manifest
  - repo: https://github.com/asottile/seed-isort-config
    rev: v2.2.0
    hooks:
      - id: seed-isort-config
        name: isort seed config
        always_run: false
        types: [python]
  - repo: https://github.com/timothycrosley/isort
    rev: 5.6.4
    hooks:
      - id: isort
        additional_dependencies:
          - toml
  - repo: https://github.com/asottile/setup-cfg-fmt
    rev: v1.15.1
    hooks:
      - id: setup-cfg-fmt
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/bandit
    rev: 1.6.2
    hooks:
      - id: bandit
        args: [--recursive, --quiet, --skip=B322]
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
      - id: flake8 # E***, W***, F***
        additional_dependencies:
          - dlint # DUO***
          - flake8-2020 # YTT***
          - flake8-bugbear # B***
          - flake8-builtins # A***
          - flake8-comprehensions # C4**
          - flake8-deprecated # D***
          - flake8-variables-names # VNE***
          - mccabe # C9**
          - pep8-naming # N8**
  #- repo: https://github.com/PyCQA/pylint
  #  rev: master
  #  hooks:
  #    - id: pylint
